from pathlib import Path

MODEL_PATH = Path("nifty50_model.joblib")

NIFTY50_TICKERS = [
    "RELIANCE.NS",
    # "HDFCBANK.NS","INFY.NS","HDFCLIFE.NS","ICICIBANK.NS","TCS.NS",
    # "KOTAKBANK.NS","HINDUNILVR.NS","SBIN.NS","BHARTIARTL.NS","ITC.NS","ASIANPAINT.NS",
    # "AXISBANK.NS","LT.NS","MARUTI.NS","SUNPHARMA.NS","TITAN.NS","BAJFINANCE.NS",
    # "WIPRO.NS","ULTRACEMCO.NS","NESTLEIND.NS","TATAMOTORS.NS","JSWSTEEL.NS",
    # "POWERGRID.NS","NTPC.NS","TECHM.NS","ONGC.NS","COALINDIA.NS","TATASTEEL.NS",
    # "HCLTECH.NS","M&M.NS","ADANIPORTS.NS","GRASIM.NS","CIPLA.NS","INDUSINDBK.NS",
    # "BRITANNIA.NS","HEROMOTOCO.NS","DRREDDY.NS","EICHERMOT.NS","BPCL.NS",
    # "SHRIRAMFIN.NS","DIVISLAB.NS","BAJAJFINSV.NS","UPL.NS","IOC.NS",
    # "HINDALCO.NS","VEDL.NS","GAIL.NS","BAJAJ-AUTO.NS","ADANIENT.NS"
]